[vars]
local_repo = "$HOME/.cache/local_repo/x86_64"

[tasks.create-local]
description = "Create and init the local AerynOS repo"
run = """
mkdir -p ~/.cache/local_repo/x86_64
moss index ~/.cache/local_repo/x86_64
sudo moss repo add local "file://{{vars.local_repo}}" -p 100
"""

[tasks.build]
description = "Build an AerynOS recipe"
usage = '''
arg "<dir>" help="directory with the stone.yaml file" default="."
'''
run = """
boulder build --compiler-cache ${usage_dir?}"
dir = "{{cwd}}
"""

[tasks.mv-local]
description = "Move .stone files into the local repo"
usage = '''
arg "<dir>" help="directory with the .stone files" default="."
'''
run = """
mv -v *.stone {{vars.local_repo}}
moss index {{vars.local_repo}}
"""
dir = "{{cwd}}"

