C %h/.config/niri/config.kdl 0644 - - - /usr/share/niri-noctalia/niri/config.kdl
C %h/.config/noctalia/config.toml 0644 - - - /usr/share/niri-noctalia/noctalia/config.toml
C %h/.config/foot/foot.ini 0644 - - - /usr/share/niri-noctalia/foot/foot.ini
